In [2]:
import pandas as pd

In [3]:
df = pd.read_parquet("pfam_output/1-cysPrx_C.parquet")

In [7]:
df

,state,mode,A,C,D,E,F,G,H,I,...,W,Y,m->m,m->i,m->d,i->m,i->i,d->m,d->d,rest
0,COMPO,match,2.28046,4.31208,2.83393,2.63913,3.90855,2.69988,3.89812,3.33401,...,3.49266,3.82715,NaN,NaN,NaN,NaN,NaN,NaN,NaN,
0,COMPO,insert,2.68618,4.42225,2.77519,2.73123,3.46354,2.40513,3.72494,3.29354,...,4.58477,3.61503,NaN,NaN,NaN,NaN,NaN,NaN,NaN,
0,COMPO,delete,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,0.00226,6.48754,7.20989,0.61958,0.77255,0.00000,-1.00000,None
0,1,match,0.29666,6.14436,6.78514,6.79783,7.06332,2.55785,7.22049,6.57837,...,8.41086,7.43107,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1A--H
0,1,insert,2.68618,4.42225,2.77519,2.73123,3.46354,2.40513,3.72494,3.29354,...,4.58477,3.61503,NaN,NaN,NaN,NaN,NaN,NaN,NaN,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
0,39,insert,2.68618,4.42225,2.77519,2.73123,3.46354,2.40513,3.72494,3.29354,...,4.58477,3.61503,NaN,NaN,NaN,NaN,NaN,NaN,NaN,
0,39,delete,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,0.00230,6.47279,7.19513,0.61958,0.77255,0.39351,1.12295,None
0,40,match,3.21541,6.27102,3.40631,3.09986,5.61658,1.23219,3.93756,5.10289,...,6.70342,3.71936,NaN,NaN,NaN,NaN,NaN,NaN,NaN,55g--C
0,40,insert,2.68618,4.42225,2.77519,2.73123,3.46354,2.40513,3.72494,3.29354,...,4.58477,3.61503,NaN,NaN,NaN,NaN,NaN,NaN,NaN,
0,40,delete,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,0.00152,6.48680,-1.00000,0.61958,0.77255,0.00000,-1.00000,None